version: '3.8'

services:
  fake_news_api:
    build: .
    container_name: ml_fake_news_container
    ports:
      - "8000:8000"
    # Подключаем папку experiments из нашего компьютера в контейнер,
    # чтобы контейнер видел нашу обученную модель model.pkl
    volumes:
      - ./experiments:/app/experiments