pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Infrastructure') {
            steps {
                script {
                    echo "Создаем конфигурационный файл .env на лету..."
                    writeFile file: '.env', text: '''POSTGRES_USER=admin
POSTGRES_PASSWORD=supersecret_pass
POSTGRES_DB=fakenews_db
POSTGRES_HOST=db
POSTGRES_PORT=5432'''

                    echo "Принудительно убиваем зависшие контейнеры с такими же именами..."
                    // Убиваем контейнеры напрямую через глобальный docker, если они существуют
                    bat "docker rm -f postgres_db fastapi_model || exit 0"

                    echo "Поднимаем базу данных и приложение..."
                    bat "docker-compose down -v || exit 0"
                    bat "docker-compose up --build -d"

                    // Даем PostgreSQL время на запуск
                    sleep time: 10, unit: 'SECONDS'
                }
            }
        }

        stage('Run Functional Tests') {
            steps {
                script {
                    echo "Запуск функционального тестирования..."
                    bat "docker-compose exec -T web pytest tests/"
                }
            }
        }
    }

    post {
        always {
            echo "Очистка тестовой среды..."
            bat "docker-compose down -v || exit 0"
        }
    }
}