pipeline {
    agent any

    environment {
        // Учетные данные DockerHub
        DOCKERHUB_CREDS = credentials('dockerhub_creds')
        // Твой логин и имя образа
        IMAGE_NAME = "твой_логин_dockerhub/fakenews_model"
        IMAGE_TAG = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    echo "Сборка Docker образа FastAPI..."
                    // Заменили sh на bat
                    bat "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                script {
                    echo "Авторизация и отправка образа в DockerHub..."
                    // Заменили sh на bat. В Windows cmd используем echo для передачи пароля
                    bat "echo %DOCKERHUB_CREDS_PSW% | docker login -u %DOCKERHUB_CREDS_USR% --password-stdin"
                    bat "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }
    }
}